model_list:
  - model_name: "deepseek-r1:1.5b"             
    litellm_params:
      model: "ollama/deepseek-r1:1.5b"
      api_base: "http://ollama:11434"
  - model_name: "lamma32"
    litellm_params:
      model: "ollama/llama3.2:1b"
      api_base: "http://ollama:11434"